### ISSUE TITLE
"Required packages" page contains code that overflows 

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/workshop03#34]
Code in the "Required packages" page overflows. 

One option is to divide the content of this slide into two columns and correctly indent the code so that one does not need to scroll to copy the code.

**Comment by katherinehebert** [comment]
Hey, Pedro! This change has previously been made in the English presentation (still needs to be done for French, but that's in progress). We are having rendering issues due to the installation of plotly (and some other unresolved issues...) so the PDF slides are not the most up-to-date version fyi!

**Comment by katherinehebert** [comment]
This issue was addressed in commit [66aa30b](https://github.com/QCBSRworkshops/workshop03/commit/66aa30b1d89774c6203e1e50bc27f9edbdef0369).
