### ISSUE TITLE
Learning objectives needs to be less general and more accurate

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/workshop03#35]
There is a first "Learning objectives" page that contains just one objective for this workshop. A few slides after, there is another page containing new learning objectives, but that still need to be more precise.

Learning objectives should be rewritten considering the entire content of the workshop and following [Bloom's taxonomy](https://tips.uark.edu/using-blooms-taxonomy/).

**Comment by katherinehebert** [comment]
This issue was addressed in commit [66aa30b](https://github.com/QCBSRworkshops/workshop03/commit/66aa30b1d89774c6203e1e50bc27f9edbdef0369).
