### ISSUE TITLE
Important modifications to be applied to Workshop 3

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/workshop03#5]
Before developing and modifying this workshop, please read through the [presenter and developer protocol](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#guidelines) **carefully** and refer back to it regularly as you work.

### Specific to adapting workshops to a remote framework:

- [x] **Fit this workshop to a 3-hour format**. The duration of this workshop should be ~3 hours (including exercises and one or two breaks of 5 minutes; excluding longer breaks). To fit this format, please add, edit, or **hide** slides from existing workshops. You can begin by hiding repetitive examples, non-essential slides, or some of the additional advanced slides that are included at the end of some workshops. Some workshops will be more difficult to shorten than others, due to their subject matter. It is not a problem to let these workshops run slightly over 3 hours to guarantee accurate and complete information. (Use your judgment). DO NOT delete slides. Use the `instruction: hidden_remote` tag. See an example below:

```
---
instruction: hidden_remote

# Slide title: I love statistics!

### Content: Amazing!
---
```
- [x] **Develop new or adapt current exercises to better suit the remote workshop format and the use of breakout rooms**. Exercises should be informative and engaging. Remember to leave time for students to work through exercises and ask questions. Refer to [these guidelines](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#active-learning) to find suggestions of exercises promoting active learning. You may use additional resources to create the exercises.

### Specific to slide structure, grammar and style

- [x] **Ensure code is working correctly and that code matches workshop presentation**. Continue to check this as you make changes.

- [x] **Proofread correcting spelling, grammar, or punctuation errors**.

- [x] **Look for and correct the content of slides that overflow the screen**.

- [x] **Look for and correct prose that mentions function names, object names, package names and code chunks that do not use backticks**.

- [x] **Look for and correct unnecessary abbreviations (e.g. use do not instead of don’t).**

- [x] **Correct unnecessary long sentences**.

- [x] **Ensure that the slides are written in a consistent style, which helps with the flow of workshops and student understanding**. This is especially important when working collaboratively with other developers.

- [x] **Include presenter notes to the slides you modify**. You can write notes for yourself to read in the presenter mode (press the keyboard shortcut `p`). These notes are written under three question marks `???`. See the example below:

```
---
The content of this workshop is essential for your graduate studies.

???

Note: _The presenter should sing this slide to the participants_.
---
```
### Specific to the translation of this workshop

- [x] **Add and translate the modified content to the French version of the workshop**.

- [x] **Proofread and correct spelling, grammar and punctuation errors**.

- [x] **Correct unnecessary long sentences**.

### Specific to this workshop

- [x] Solve issue #4 
- [x] Code indentation is very important to ensure readability in this workshop, and it is already done fairly consistently in this workshop. However, the `labs()` arguments tend to not be indented in these slides, and the demos of different colour palettes as well. There may be other occurrences of this as well. Each `ggplot2` function should begin on a new line, and the arguments themselves should also be on a new line when they are longer to avoid wrapping, such as labels. Please check the indentation carefully.
- [x] This workshop will be most effective when its structure reflects the process of building a plot. This is already done pretty well in the current workshop, but this structure could be made more apparent (e.g. by showing the progress in the "pipeline" of tasks when creating a figure as we flow from section to section). In general, please check that section headers clearly separate different steps of the process. An illustration of the plot-making process could also be effective, but it is not essential.
- [x] If this workshop needs to be reduced in size for the remote setting, a good place to start would be to check for redundant or somewhat overlapping demonstrations, such as the different ways to set color scales. In these cases, try to keep the demonstrations that are the most commonly useful (e.g. `ColorBrewer`, `viridis`, etc.).
- [x] Slide 18: Linking to [this gallery](https://exts.ggplot2.tidyverse.org/gallery/) of R extensions would be a good idea in addition to/to replace the existing link, as this is updated more regularly.
- [x] Slide 29: Given that this is a workshop about `ggplot2`, this workshop should show ways to exploring data structure in `ggplot2` (or in "base R"), rather than the `psych` package. This is also the only use and mention of the `psych` package in this workshop.
- [x] Slide 46: We should avoid showing the `rainbow` palette, which is [not recommended for visualizing data](https://clauswilke.com/dataviz/color-pitfalls.html#using-non-monotonic-color-scales-to-encode-data-values).
- [x] Slide 49-50: We should show how to produce the figure of color-vision-deficiency simulations with `cvd_grid()`.
- [x] [ _Suggestion_ ] Challenge 2 is a great opportunity for a Breakout Room challenge - the datasets can be assigned to different groups, and participants can share the figures they made together.
- [x] We should introduce `theme_set()` as an available tool to get around the verbosity of `ggplot2` syntax when making many figures.
- [x] `ggThemeAssist`: this is a great tool to show, but it would also be a good idea to show the `theme()` code and identify what each command is doing. [This](https://isabella-b.com/blog/ggplot2-theme-elements-reference/) would also be a good reference to link or show.
- [ ] Slide 74: The different `geom_*` could be introduced earlier - if the presentation follows the process of building a plot, choosing plot type is one of the first decisions to make. However, it makes sense to work with a scatter plot first to demonstrate aesthetic mapping, theme, etc. elements to keep things simple. This slide would then be a callback to the other `geom` options. This [page](https://www.data-to-viz.com/) would also be a great link to include, to help people make decisions based on the data they would like to visualize. 
- [x] Violin plots: We should also show how to add summary statistics to the violin plot, such as the mean.
- [x] Arrange plots: Replace the `ggarrange` content to the `patchwork` package ([see here](https://patchwork.data-imaginist.com/)), to arrange plots in a more flexible and easily implemented way.

Only close this issue after all cases have been ticked and verified.

**Comment by jakelawlor** [comment]
Addressed most issues and reformatted many sides. Did not find alignment errors, and did not translate. See PR 1.

**Comment by katherinehebert** [comment]
Closing this issue. Translation was done last year in PR #4. All important modifications have been applied, thanks @jakelawlor and @mhBrice!
